version: '3'
services:
  postgres:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./db
    environment:
      - POSTGRES_PASSWORD=something_secure
      - POSTGRES_DB=flashcards
  client:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 3000:3000
  server:
    restart: on-failure
    build: 
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 5000:5000
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=flashcards
      - PGPASSWORD=something_secure
      - PGPORT=5432
